title: David Alves
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://david27alves.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Sobre
   url: /about
 - title: Contato
   url: /contact

social:
   github: david27alves
   twitter: DaviidAllves
   facebook: fcodavid27
   email: david27alves@hotmail.com

google_analytics: ""
